# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaccard_index <- function(s1, s2) {
    .Call(`_treecompareR_jaccard_index`, s1, s2)
}

get_jaccard <- function(list1, list2) {
    .Call(`_treecompareR_get_jaccard`, list1, list2)
}

get_children <- function(this_node, nodes, parents) {
    .Call(`_treecompareR_get_children`, this_node, nodes, parents)
}

get_descendants <- function(these_nodes, nodes, parents) {
    .Call(`_treecompareR_get_descendants`, these_nodes, nodes, parents)
}

calc_IC <- function(these_nodes, nodes, parents) {
    .Call(`_treecompareR_calc_IC`, these_nodes, nodes, parents)
}

get_parents <- function(these_nodes, nodes, parents) {
    .Call(`_treecompareR_get_parents`, these_nodes, nodes, parents)
}

get_ancestors <- function(these_nodes, nodes, parents) {
    .Call(`_treecompareR_get_ancestors`, these_nodes, nodes, parents)
}

get_MRCA <- function(node1, node2, nodes, parents) {
    .Call(`_treecompareR_get_MRCA`, node1, node2, nodes, parents)
}

get_similarity <- function(nodes1, nodes2, tree_nodes, tree_parents, sim_metric) {
    .Call(`_treecompareR_get_similarity`, nodes1, nodes2, tree_nodes, tree_parents, sim_metric)
}

